#pragma once
// ============================================================================
// AIOverhangDetector.hpp
// ============================================================================
// AI-assisted support placement using a self-contained Random Forest
// classifier.  No external ML library is required — the entire model is
// implemented in pure C++17 using only the standard library and Eigen (already
// a project dependency).
//
// Architecture overview
// ─────────────────────
//  1. OverhangFeatureExtractor  — extracts 12 geometric features per candidate
//     overhang region from the sliced layer data.
//  2. DecisionTree              — a single CART decision tree (binary splits on
//     feature thresholds).
//  3. RandomForest              — ensemble of N trees; prediction is the mean
//     probability across all trees.
//  4. AIOverhangDetector        — top-level class that:
//       a. Builds / loads the forest (pre-trained weights embedded as C arrays).
//       b. Runs feature extraction on each layer.
//       c. Returns a list of ExPolygons that need support, with a confidence
//          score per region.
//       d. Optionally blends the AI result with the classic angle-threshold
//          result for a hybrid mode.
//
// Feature vector (12 dimensions)
// ───────────────────────────────
//  [0]  overhang_area_mm2          — area of the candidate overhang region
//  [1]  overhang_perimeter_mm      — perimeter length of the region
//  [2]  support_area_ratio         — fraction of region area that is unsupported
//  [3]  mean_overhang_angle_deg    — mean face normal angle from vertical
//  [4]  max_overhang_angle_deg     — maximum face normal angle from vertical
//  [5]  layer_height_mm            — current layer height
//  [6]  z_height_mm                — absolute Z of the layer
//  [7]  aspect_ratio               — bbox width / bbox height of the region
//  [8]  compactness                — 4π·area / perimeter² (circularity)
//  [9]  lower_support_fraction     — fraction of region supported by lower layer
//  [10] bridge_span_mm             — estimated longest unsupported span
//  [11] sharp_tail_flag            — 1.0 if region is a sharp tail, else 0.0
//
// Training data
// ─────────────
// The forest is pre-trained on synthetic data generated by running the classic
// angle-threshold detector on a diverse set of models and labelling each
// candidate region as "needs support" (1) or "does not need support" (0).
// The embedded weights below were produced by that offline training process.
// Users can retrain by calling AIOverhangDetector::train_and_save() and
// embedding the resulting weights.
//
// ============================================================================

#ifndef slic3r_AIOverhangDetector_hpp_
#define slic3r_AIOverhangDetector_hpp_

#include <array>
#include <vector>
#include <string>
#include <memory>
#include <functional>
#include <cmath>
#include <algorithm>
#include <numeric>
#include <random>
#include <cassert>
#include <limits>

#include "../ExPolygon.hpp"
#include "../Point.hpp"
#include "../TriangleMesh.hpp"

namespace Slic3r {

class PrintObject;
class Layer;

namespace AI {

// ============================================================================
// Constants
// ============================================================================

static constexpr int   FEATURE_DIM        = 12;
static constexpr int   FOREST_N_TREES     = 50;
static constexpr int   TREE_MAX_DEPTH     = 8;
static constexpr int   MIN_SAMPLES_SPLIT  = 4;
static constexpr float DEFAULT_THRESHOLD  = 0.45f;  // probability threshold for "needs support"

// ============================================================================
// Feature vector
// ============================================================================

using FeatureVec = std::array<float, FEATURE_DIM>;

// Names for documentation / debugging
inline const char* feature_name(int i) {
    static const char* names[FEATURE_DIM] = {
        "overhang_area_mm2",
        "overhang_perimeter_mm",
        "support_area_ratio",
        "mean_overhang_angle_deg",
        "max_overhang_angle_deg",
        "layer_height_mm",
        "z_height_mm",
        "aspect_ratio",
        "compactness",
        "lower_support_fraction",
        "bridge_span_mm",
        "sharp_tail_flag"
    };
    return (i >= 0 && i < FEATURE_DIM) ? names[i] : "unknown";
}

// ============================================================================
// Training sample
// ============================================================================

struct TrainingSample {
    FeatureVec features;
    int        label;   // 0 = no support needed, 1 = support needed
};

// ============================================================================
// Prediction result for one overhang region
// ============================================================================

struct OverhangPrediction {
    ExPolygon region;           // the candidate overhang polygon
    float     probability;      // P(needs_support) in [0, 1]
    bool      needs_support;    // probability >= threshold
    int       layer_idx;        // 0-based layer index
    float     z_mm;             // layer print_z in mm
    FeatureVec features;        // for debugging / visualization
};

using OverhangPredictions = std::vector<OverhangPrediction>;

// ============================================================================
// Decision Tree node
// ============================================================================

struct TreeNode {
    // Internal node fields
    int   feature_idx  = -1;
    float threshold    = 0.f;
    int   left_child   = -1;   // index into nodes array
    int   right_child  = -1;

    // Leaf node fields
    float leaf_value   = 0.f;  // mean label in leaf (probability)
    bool  is_leaf      = false;
};

// ============================================================================
// Decision Tree
// ============================================================================

class DecisionTree {
public:
    DecisionTree() = default;

    // Build tree from training data (indices into samples vector)
    void fit(const std::vector<TrainingSample>& samples,
             const std::vector<int>&            indices,
             int                                max_depth,
             int                                min_samples_split,
             std::mt19937&                      rng,
             int                                max_features);

    // Predict probability for a single sample
    float predict(const FeatureVec& x) const;

    // Serialization (simple binary format)
    void serialize(std::vector<uint8_t>& buf) const;
    bool deserialize(const uint8_t* data, size_t size, size_t& offset);

    const std::vector<TreeNode>& nodes() const { return m_nodes; }

private:
    std::vector<TreeNode> m_nodes;

    int build_node(const std::vector<TrainingSample>& samples,
                   const std::vector<int>&            indices,
                   int                                depth,
                   int                                max_depth,
                   int                                min_samples_split,
                   std::mt19937&                      rng,
                   int                                max_features);

    // Gini impurity for a set of labels
    static float gini(const std::vector<int>& labels);

    // Best split for a subset of samples
    static bool best_split(const std::vector<TrainingSample>& samples,
                           const std::vector<int>&            indices,
                           const std::vector<int>&            feature_subset,
                           int&                               best_feat,
                           float&                             best_thresh,
                           float&                             best_gain);
};

// ============================================================================
// Random Forest
// ============================================================================

class RandomForest {
public:
    RandomForest() = default;

    // Train on labelled samples
    void fit(const std::vector<TrainingSample>& samples,
             int                                n_trees     = FOREST_N_TREES,
             int                                max_depth   = TREE_MAX_DEPTH,
             int                                min_samples = MIN_SAMPLES_SPLIT,
             unsigned                           seed        = 42);

    // Predict probability for a single sample
    float predict_proba(const FeatureVec& x) const;

    // Predict label (0 or 1) using threshold
    int predict(const FeatureVec& x, float threshold = DEFAULT_THRESHOLD) const;

    // Serialization
    std::vector<uint8_t> serialize() const;
    bool deserialize(const std::vector<uint8_t>& data);

    bool is_trained() const { return !m_trees.empty(); }
    int  n_trees()    const { return static_cast<int>(m_trees.size()); }

    // Feature importance (mean decrease in Gini across all trees)
    std::array<float, FEATURE_DIM> feature_importances() const;

private:
    std::vector<DecisionTree> m_trees;
};

// ============================================================================
// Feature Extractor
// ============================================================================

class OverhangFeatureExtractor {
public:
    // Extract features for a single candidate overhang region on a given layer.
    // lower_layer may be nullptr for the first layer.
    static FeatureVec extract(
        const ExPolygon& overhang_region,
        const Layer*     current_layer,
        const Layer*     lower_layer,
        const indexed_triangle_set& its,   // mesh for face normal computation
        double           layer_height_mm,
        bool             is_sharp_tail = false);

    // Extract features for all overhang regions on a layer
    static std::vector<FeatureVec> extract_layer(
        const ExPolygons& overhang_regions,
        const Layer*      current_layer,
        const Layer*      lower_layer,
        const indexed_triangle_set& its,
        double            layer_height_mm);

private:
    // Compute overhang angles for faces whose projection overlaps the region
    static void compute_overhang_angles(
        const ExPolygon&            region,
        const indexed_triangle_set& its,
        float                       layer_z_bottom_mm,
        float                       layer_z_top_mm,
        float&                      mean_angle_deg,
        float&                      max_angle_deg);

    // Estimate longest unsupported span (bridge span)
    static float estimate_bridge_span(const ExPolygon& region);

    // Fraction of region area covered by lower layer
    static float lower_support_fraction(
        const ExPolygon& region,
        const Layer*     lower_layer);
};

// ============================================================================
// Synthetic training data generator
// ============================================================================

class SyntheticTrainingDataGenerator {
public:
    // Generate N synthetic training samples using the classic angle-threshold
    // heuristic as ground truth.  This is used to bootstrap the model without
    // requiring real labelled data.
    static std::vector<TrainingSample> generate(
        int    n_samples       = 5000,
        float  support_angle   = 45.f,   // degrees — classic threshold
        unsigned seed          = 12345);
};

// ============================================================================
// Main AI Overhang Detector
// ============================================================================

class AIOverhangDetector {
public:
    // Configuration
    struct Config {
        float   probability_threshold  = DEFAULT_THRESHOLD;
        bool    hybrid_mode            = true;   // blend AI + classic results
        float   hybrid_classic_weight  = 0.3f;   // weight of classic result in hybrid
        bool    use_pretrained_model   = true;   // use embedded weights
        int     n_trees                = FOREST_N_TREES;
        int     max_depth              = TREE_MAX_DEPTH;
        float   classic_angle_deg      = 45.f;   // classic threshold for hybrid
        bool    verbose                = false;
    };

    explicit AIOverhangDetector(const Config& cfg = Config{});

    // Initialize: load pre-trained model or train from scratch
    void init();

    // Run AI overhang detection on a PrintObject.
    // Returns predictions for all layers.
    OverhangPredictions detect(const PrintObject& object) const;

    // Run on a single layer
    std::vector<OverhangPrediction> detect_layer(
        const Layer*                layer,
        const Layer*                lower_layer,
        const indexed_triangle_set& its) const;

    // Get ExPolygons that need support (convenience wrapper)
    ExPolygons get_support_regions(const PrintObject& object) const;

    // Train the model from scratch using synthetic data
    void train(int n_samples = 8000, unsigned seed = 42);

    // Serialize / deserialize model weights
    std::vector<uint8_t> serialize_model() const;
    bool                 load_model(const std::vector<uint8_t>& data);

    // Access the underlying forest
    const RandomForest& forest() const { return m_forest; }
    RandomForest&       forest()       { return m_forest; }

    bool is_ready() const { return m_forest.is_trained(); }

    // Feature importance report (for debugging)
    std::string feature_importance_report() const;

private:
    Config       m_config;
    RandomForest m_forest;

    // Load the embedded pre-trained weights (defined in .cpp)
    bool load_pretrained_weights();

    // Classic angle-threshold overhang detection (used in hybrid mode)
    ExPolygons classic_detect_layer(
        const Layer* layer,
        const Layer* lower_layer,
        float        angle_deg) const;

    // Merge AI and classic results in hybrid mode
    ExPolygons merge_hybrid(
        const std::vector<OverhangPrediction>& ai_preds,
        const ExPolygons&                      classic_regions,
        float                                  classic_weight) const;
};

} // namespace AI
} // namespace Slic3r

#endif // slic3r_AIOverhangDetector_hpp_
